# Define the services and applications that make up your application.
services:
  user_service:
    build: ./backend/user_service # Path to the directory containing the Dockerfile for building the user service image.
    ports:
      - 5001:5001 # Maps port 5001 on the host to port 5001 in the container, making the app accessible on the host.
    networks:
      - app-network

  question_service:
    build: 
      context: ./backend/question_service # Path to the directory containing the Dockerfile for building the question service image.
      args:
        USER_SERVICE_BACKEND_URL: ${USER_SERVICE_BACKEND_URL}
    ports:
      - 5002:5002 # Maps port 5002 on the host to port 5002 in the container, making the app accessible on the host.
    networks:
      - app-network 
    depends_on:
      - user_service

  frontend:
    build: 
      context: ./frontend
      args: 
        VITE_QUESTION_SERVICE_BACKEND_URL: ${VITE_QUESTION_SERVICE_BACKEND_URL}
    ports:
      - 3000:80
    networks:
      - app-network

networks:
  app-network: # Defines a network named 'app-network'.
    driver: bridge # Uses the bridge driver for the network, which is the default and most common network type in Docker.
